name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine tag name
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Sync organize variant
        run: |
          node scripts/sync_shared.mjs

      - name: Package extensions
        run: |
          mkdir -p dist
          # Full variant from repository root
          zip -r "dist/tidymark-full-${TAG_NAME}.zip" \
            manifest.json \
            icons \
            _locales \
            src \
            services \
            README.md LICENSE
          # Organize-only variant from extensions/organize
          cd extensions/organize
          zip -r "../../dist/tidymark-organize-${TAG_NAME}.zip" \
            manifest.json \
            icons \
            _locales \
            src \
            services
          cd ../..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: TidyMark ${{ env.TAG_NAME }}
          files: |
            dist/tidymark-full-${{ env.TAG_NAME }}.zip
            dist/tidymark-organize-${{ env.TAG_NAME }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}